# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
    inputs:
      menu:
        description: 'Menu'
        required: true
        default: 'warning' 
        type: choice
        options:
        - carne
        - pesce
        - torta di riso 
      print_tags:
        description: 'True to print to STDOUT'
        required: true 
        type: boolean 
      tags:
        description: 'Test scenario tags'
        required: true 
        type: string
        default: 'none'
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 

jobs:
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ github.event.inputs.print_tags == 'true' }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ github.event.inputs.tags }} 
    

