# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
    inputs:
      menu:
        description: 'Menu'
        required: true
        default: 'torta di riso' 
        type: choice
        options:
        - carne
        - pesce
        - torta di riso 
      print_tags:
        description: 'True to print to STDOUT'
        required: true 
        type: boolean 
      tags:
        description: 'Test scenario tags'
        required: true 
        type: string
        default: 'none'
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
      imagetag:
        description: 'New image tag to be deployed'
        required: true
        type: string

jobs:
  firstjob:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{github.event.inputs.imagetag}}

      # Runs a set of commands using the runners shell
      - name: git
        run: |
          # setup the username and email. I tend to use 'GitHub Actions Bot' with no email by default
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git status
          git tag
          git describe
